Add win_delay_load_hook
awslabs/aws-crt-nodejs pull request #525
Opened 2024-01-18 01:04 UTC by xiazhvera

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-01-18 15:36 UTC, bretambrose reviewed
I'm very uncomfortable with making a change that affects everyone and switches from C to C++.  I think we should push the maintainer of cmake-js to add a build option that would cause their copy of win_delay_load_hook to be treated as C.

The primary blocker there looks to be finding a replacement for the decltype shorthand in the last line.

2024-01-18 17:19 UTC, xiazhvera commented
> I'm very uncomfortable with making a change that affects everyone and switches from C to C++. I think we should push the maintainer of cmake-js to add a build option that would cause their copy of win_delay_load_hook to be treated as C.
> 
> The primary blocker there looks to be finding a replacement for the decltype shorthand in the last line. It sure seems like it could just be replaced by the actual function signature above since it appears to be a fixed ABI contract.

We can probably add our own win_delay_load_hook implementation instead of using cmakejs version. Let me update it.

2024-01-19 19:29 UTC, bretambrose reviewed
Is there any way to add a CI step that makes and runs a simple electron exe on windows?

2024-01-20 00:06 UTC, xiazhvera commented
> Is there any way to add a CI step that makes and runs a simple electron exe on windows?

As all our samples are in js-v2 branch, the electron sample would also launched there:https://github.com/aws/aws-iot-device-sdk-js-v2/pull/398 (WIP, still need setup CI for it.)

I also created an quick electron sample to verify the change here:
https://github.com/awslabs/aws-crt-nodejs/pull/526. 
Checkout [windows](https://github.com/awslabs/aws-crt-nodejs/actions/runs/7590555985/job/20677261356#logs) and  [windows-vc14-x86](https://github.com/awslabs/aws-crt-nodejs/actions/runs/7590555985/job/20677261949?pr=526#logs)

2024-01-26 00:32 UTC, bretambrose approved these changes

2024-01-26 00:34 UTC, bretambrose requested changes

2024-01-26 00:34 UTC, bretambrose commented on source/windows/win_delay_load_hook.c
> +
Actually hold up.  We should make sure everything is kosher license-wise with this.

2024-01-26 00:34 UTC, bretambrose commented on source/windows/win_delay_load_hook.c
> +            if (_stricmp(pdli->szDll, "node.exe") != 0) {
Also let's not use _stricmp

2024-02-02 21:04 UTC, bretambrose approved these changes

2024-02-07 22:30 UTC, merged